/*************************************************************************************\
 ***
 *** Simulation frame file :  picontroller_pcf.c
 *** Code generation unit  :  pipt1/picontroller/Subsystem/picontroller
 ***
 *** Generated by dSPACE TargetLink Version 5.2p1 from 23-Mar-2022
 *** Generation date: 04-Jan-2024 12:50:59
\*************************************************************************************/

#ifndef PICONTROLLER_PCF_C
#define PICONTROLLER_PCF_C

/* standard definitions and includes */
#if defined(TL_STACK_MEASUREMENT) || defined(TL_TIME_MEASUREMENT)
#include "ts_frame.h"
#endif


/* include frame header file (if exist) and TL subsystem header file(s) */
#ifdef TL_FRAME
#include "picontroller_frm.h"
#endif 
#include "picontroller_fri.h"

#ifdef __cplusplus
extern "C" {
#endif

#if !defined(TL_FRAME) && !defined(TL_CODE_SFCN) && !defined(RT) && !defined(TL_FRAME_PROVIDE_ROOT_FUNCTION_INFO) 

#ifdef FORBID_OPT
void (* g_FcnTable_a[])(void)        = {(void *)picontroller};
#endif /* #ifdef FORBID_OPT */

#else /* #ifndef TL_FRAME */

extern void CallFcn_a1(void);

#ifdef FORBID_OPT
void (* g_FcnTable_a[])(void)        = {(void *)CallFcn_a1};
#endif /* #ifdef FORBID_OPT */


#ifdef TL_FRAME_PROVIDE_ROOT_FUNCTION_INFO
tl_sim_UInt16 g_NumOfStepFcn_a       = 1;
tl_sim_UInt16 g_NumOfRestartFcn_a    = 0;
tl_sim_UInt16 g_NumOfInitFcn_a       = 0;
tl_sim_UInt16 g_NumOfTermFcn_a       = 0;

void (* g_StepFcnTable_a[])(void)    = {(void *)CallFcn_a1};
void (* g_RestartFcnTable_a[])(void) = {0L};
void (* g_InitFcnTable_a[])(void)    = {0L};
void (* g_TermFcnTable_a[])(void)    = {0L};
#endif /* #ifdef TL_FRAME_PROVIDE_ROOT_FUNCTION_INFO */

#ifdef CTC_CODE_COVERAGE
extern void ctc_append_all(void);
#endif /* #ifdef CTC_CODE_COVERAGE */

/**************************************************************************\
   Variables declarations
\**************************************************************************/

#ifdef TL_STACK_MEASUREMENT
/* variables for stack consumption measurement */
tl_sim_UInt32 g_TsStackSize_a;
#endif

#ifdef TL_TIME_MEASUREMENT
/* variables for execution time measurement */
tl_sim_UInt32 g_TsExecTime_a;
#endif



/**************************************************************************\
    Caller function for production code function:  "picontroller" 
\**************************************************************************/
void CallFcn_a1(void)
{

#ifdef LOG_VARS
   /* reset logstruct */
   memset((void*)(&log_struct_a),0,sizeof(log_struct_a));
#endif


#ifdef TL_STACK_MEASUREMENT
   /* setup stack consumption measurement */
   TsInitStack();
#endif

#ifdef TL_TIME_MEASUREMENT
   /* setup execution time measurement */
   TsInitWatch();
   TsStartWatch();
#endif

   /* call the production code function */
   picontroller();

#ifdef TL_TIME_MEASUREMENT
   /* stop execution time counter */
   TsStopWatch();
#endif

#ifdef TL_STACK_MEASUREMENT
   /* get stacksize */
   g_TsStackSize_a = TsGetStackSize();
#endif

#ifdef TL_TIME_MEASUREMENT
   /* get execution time */
   g_TsExecTime_a = TsGetWatch() - g_TsExecTimeError;
#endif


} /* CallFcn_a1 */


/**************************************************************************\
   Caller function for CTC code coverage support
\**************************************************************************/
#ifdef CTC_CODE_COVERAGE
void CallCtcAppend_a(void)
{
   /* call the function to saving CTC data */
   ctc_append_all();
}
#endif /* #ifdef CTC_CODE_COVERAGE */

#endif /* #ifndef TL_FRAME */

#ifdef __cplusplus
}
#endif

#endif /* PICONTROLLER_PCF_C */
