/**************************************************************************************************\
 *** 
 *** Simulink model       : pipt1
 *** TargetLink subsystem : pipt1/picontroller
 *** Codefile             : picontroller.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-01-04 12:50:58
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnSignedness
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 5
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1            picontroller
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** 
 *** TargetLink version      : 5.2p1 from 23-Mar-2022
 *** Code generator version  : Build Id 5.2.0.27 from 2022-03-21 17:27:57
\**************************************************************************************************/

#ifndef PICONTROLLER_C
#define PICONTROLLER_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "tl_defines_a.h"
#include "picontroller.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   STATIC_CAL: static calibratable parameters (ROM) | Width: 8
\**************************************************************************************************/
STATIC_CAL Int8 P_Sa1_Ki = 26 /* 0.4 */; /* 
   LSB: 2^-6 OFF: 0 MIN/MAX: -2 .. 1.984375
   Description: integral gain factor */
STATIC_CAL Int8 P_Sa1_Kp = 80 /* 5. */; /* 
   LSB: 2^-4 OFF: 0 MIN/MAX: -8 .. 7.9375
   Description: proportional gain factor */

/**************************************************************************************************\
   STATIC_DISP: static observable variables (RAM) | Width: 16
\**************************************************************************************************/
STATIC_DISP Int16 Sa1_sU; /* 
   LSB: 2^-6 OFF: 0 MIN/MAX: -512 .. 511.984375
   Description: this is the controller output signal */

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 16
\**************************************************************************************************/
UInt16 Sa1_REF; /* LSB: 2^-11 OFF: 0 MIN/MAX: 0 .. 31.99951171875 */
Int16 Sa1_U; /* LSB: 2^-6 OFF: 0 MIN/MAX: -512 .. 511.984375 */
UInt16 Sa1_Y; /* LSB: 2^-11 OFF: 0 MIN/MAX: 0 .. 31.99951171875 */

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      picontroller
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void picontroller(void)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   Int16 Sa1_e; /* LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375 */
   Int16 Sa1_x; /* LSB: 2^-6 OFF: 0 MIN/MAX: -512 .. 511.984375 */

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 16
    */
   static UInt16 X_Sa1_Unit_Delay = 0; /* LSB: 2^-6 OFF: 0 MIN/MAX: 0 .. 1023.984375 */

   LOG_VAR(a, _Sa1_Y, Sa1_Y);

   /* Sum: picontroller/e */
   Sa1_e = (Int16) ((((Int32) Sa1_REF) - ((Int32) Sa1_Y)) >> 1);
   LOG_VAR(a, _Sa1_e, Sa1_e);

   /* Sum: picontroller/x */
   Sa1_x = (Int16) (((UInt16) (Int16) (Sa1_e >> 4)) + X_Sa1_Unit_Delay);

   /* Unit delay: picontroller/Unit Delay */
   X_Sa1_Unit_Delay = (UInt16) Sa1_x;
   LOG_VAR(a, _Sa1_x, Sa1_x);

   /* Sum: picontroller/sU
      # combined # Gain: picontroller/Ki
      # combined # Gain: picontroller/Kp */
   Sa1_sU = (Int16) (((Int16) ((((Int32) Sa1_e) * ((Int32) P_Sa1_Kp)) >> 8)) + ((Int16) ((((Int32)
    Sa1_x) * ((Int32) P_Sa1_Ki)) >> 6)));
   LOG_VAR(a, _Sa1_sU, Sa1_sU);

   /* TargetLink outport: picontroller/U */
   Sa1_U = Sa1_sU;
}

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif

#endif /* PICONTROLLER_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
