#=======================================================================
# MAKE-file segment:  pipt1.mk
#
# Generated by dSPACE TargetLink Version 5.2p1 from 23-Mar-2022
# Generation date: 2024-01-04 12:51:04 
#=======================================================================


#-----------------------------------------------------------------------
# MakeFile.mk options
#-----------------------------------------------------------------------

LOGDATA=ON
MCU=x86_64
COMPILER=MSVC
BOARD=HostPC64
D_SIM=TLBuild
MakefileSupportsQuotedPath=1
COMP_ROOT=C:\Program Files (x86)\Microsoft Visual Studio\2019\VC\Tools\MSVC\14.29.30133  # directory where the compiler is installed
PROD_CODE_BUILDER=C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\ApplicationBuilder  # directory prod. code builder
UTILITY_ROOT=C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\ApplicationBuilder\bin  # directory where TL utilities are installed
DSFXP_SRC_ROOT=C:\ProgramData\dSPACE\7189E855-5013-45C1-A1AC-9D7D41874481\Archives\FxpLibSrc  # directory where DSFxp is installed
SIMULATION_PACKAGE=C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\ApplicationBuilder\BoardPackages\HostPC64\MSVC  # directory where plattform sources are installed
GENERIC_SRC_ROOT=C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\SimFiles\generic  # directory where generic sources are installed
COMP_SDK_ROOT=C:\Program Files (x86)\Windows Kits\10
SDK_VERSION=10.0.19041.0
COMP_KITS_ROOT=C:\Program Files (x86)\Windows Kits\10
COMP_VERSION=16.0
COMP_OPT=
USE_OSEK_EMULATOR=OFF
ShowAllWarnings=0
ACCESS_POINTS_DISABLE=ON
COMPILE_ONLY=OFF

TL_MAX_SIM_OBJECTS=2
TL_MAX_SIM_LISTS=7
TL_MAX_SIM_VARS=11


#-----------------------------------------------------------------------
# System/CodeGenerationUnit "pipt1/picontroller/Subsystem/picontroller":
#-----------------------------------------------------------------------

# application source file list
PICONTROLLER_APPL_SRC_FILES := \
   ".\TLBuild\pipt1\HostPC64_MSVC\picontroller.c" \

# application source file list (compiled as C++ files)
PICONTROLLER_APPL_SRC_CPP_FILES := \


# application library file list
PICONTROLLER_APPL_LIB_FILES := \


# application object file list
PICONTROLLER_APPL_OBJ_FILES := \


# production code frame source file list
PICONTROLLER_CALLER_FCN_SRC_FILES := \
   ".\TLBuild\pipt1\HostPC64_MSVC\picontroller_fri.c" \
   ".\TLBuild\pipt1\HostPC64_MSVC\picontroller_pcf.c" \

# production code frame source file list (compiled as C++ files)
PICONTROLLER_CALLER_FCN_SRC_CPP_FILES := \


# file dependencies
picontroller.obj :  "picontroller.c" "tl_defines_a.h" "picontroller.h" "tl_basetypes.h"
picontroller_fri.obj :  "picontroller_fri.c" "picontroller_fri.h" "tl_defines_a.h" "tl_basetypes.h" "picontroller_frm.h"
picontroller_pcf.obj :  "picontroller_pcf.c" "picontroller_fri.h" "ts_frame.h"


#-----------------------------------------------------------------------
# List of RTE frame files generated by the RTE code generator
#-----------------------------------------------------------------------
RTE_FRAME_FILES := \


#-----------------------------------------------------------------------
# List of source files
#-----------------------------------------------------------------------
APPL_SRC_FILES := \
   $(PICONTROLLER_APPL_SRC_FILES) \

APPL_SRC_CPP_FILES := \
   $(PICONTROLLER_APPL_SRC_CPP_FILES) \

CALLER_SRC_FILES := \
   $(PICONTROLLER_CALLER_FCN_SRC_FILES) \
   $(RTE_FRAME_FILES) \

CALLER_SRC_CPP_FILES := \
   $(PICONTROLLER_CALLER_FCN_SRC_CPP_FILES) \
   $(RTE_FRAME_CPP_FILES) \


#-----------------------------------------------------------------------
# List of object files
#-----------------------------------------------------------------------
APPL_OBJ_FILES := \
   $(PICONTROLLER_APPL_OBJ_FILES) \


#-----------------------------------------------------------------------
# List of library files
#-----------------------------------------------------------------------
MODEL_LIB_PATH := \
   C:\Users\G2EFNBS\AppData\Local\dSPACE\7189E855-5013-45C1-A1AC-9D7D41874481\TargetLink\DSFxp\HostPC64\MSVC

MODEL_LIB_FILES := \
   $(PICONTROLLER_APPL_LIB_FILES) \

DSFXP_NAME := \
   


#-----------------------------------------------------------------------
# User-defined include paths
#-----------------------------------------------------------------------
USR_INC_PATHS := \
   ".\TLBuild\pipt1\HostPC64_MSVC" \

# [EOF]

