/**************************************************************************************************\
 *** 
 *** Simulink model       : poscontrol
 *** TargetLink subsystem : poscontrol/controller
 *** Codefile             : Controller.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-05-26 00:59:14
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnSignedness
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 5
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** SCtrl1         controller
 *** SCtrl2         controller/Linearization
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** 
 *** TargetLink version      : 5.2p1 from 23-Mar-2022
 *** Code generator version  : Build Id 5.2.0.27 from 2022-03-21 17:27:57
\**************************************************************************************************/

#ifndef CONTROLLER_C
#define CONTROLLER_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "tl_defines_Ctrl.h"
#include "Controller.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 8
\**************************************************************************************************/
const volatile Int8 LinTable[25] = 
{
   /* [0..9] */ -96, -94, -91, -87, -81, -74, -66, -56, -46, -35, 
   /* [10..19] */ -24, -12, 0, 12, 24, 35, 46, 56, 66, 74, 
   /* [20..24] */ 81, 87, 91, 94, 96
   /* -12., -11.8002765350741, -11.416413701523, -10.8544015504781, -10.1230100935865, -9.2336524499
   1286, -8.20020674803336, -7.03879956248094, -5.76755426394346, -4.4063082101256, 
   -2.97630319041666, -1.49985395487165, 0., 1.49985395487165, 2.97630319041666, 4.4063082101256, 5.
   76755426394346, 7.03879956248094, 8.20020674803336, 9.23365244991286, 
   10.1230100935865, 10.8544015504781, 11.416413701523, 11.8002765350741, 12. */
}; /* 
   LSB: 2^-3 OFF: 0 MIN/MAX: -12 .. 12
   Description: linearized output values */

/**************************************************************************************************\
   DISP: global observable variables (RAM) | Width: 16
\**************************************************************************************************/
Int16 SPI; /* 
   LSB: 2^-9 OFF: 0 MIN/MAX: -64 .. 63.998046875
   Description: controller output signal */

/**************************************************************************************************\
   GLOBAL_INTERFACE: mergeable global variables (RAM) | Width: 16
\**************************************************************************************************/
Int16 Position; /* 
   Unit: mm
   LSB: 2^-10 OFF: 0 MIN/MAX: -12 .. 12
   Description: measured position */
Int16 Reference; /* 
   Unit: mm
   LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375
   Description: reference position */
Int16 UPI; /* 
   LSB: 2^-9 OFF: 0 MIN/MAX: -64 .. 63.998046875
   Description: Controller Output */

/**************************************************************************************************\
   SCOPE_REDUCABLE_INTERFACESrToModuleLocal_Ctrl: TL CG ScopeReducedClass : derived from SCOPE_REDUC
   ABLE_INTERFACE | Width: 16
\**************************************************************************************************/
static Int16 LinPosition; /* 
   Unit: mm
   LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375
   Description: linearized position */

/**************************************************************************************************\
   STATIC_CAL: static calibratable parameters (ROM) | Width: 8
\**************************************************************************************************/
static const volatile Bool LinEnableLUT = 1; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1
   Description: enable table lookup */
static const volatile UInt8 LinGain = 85 /* 0.666666666666667 */; /* 
   LSB: 2^-7 OFF: 0 MIN/MAX: 0.3 .. 1.3
   Description: linearization factor for small scale signals */

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   StaticFcnSpecStep: Default function class for static model step functions
\**************************************************************************************************/
static void Linearization(void);

/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Controller
 *** 
 ***  DESCRIPTION:
 ***      controller function
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void Controller(void)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   Int16 SCtrl1_e; /* LSB: 2^-10 OFF: 0 MIN/MAX: -32 .. 31.9990234375 */

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 16
    */
   static Int16 X_SCtrl1_xi = 0; /* LSB: 2^-9 OFF: 0 MIN/MAX: -64 .. 63.998046875 */

   /* call of function: controller/Linearization */
   Linearization();

   /* Sum: controller/e */
   SCtrl1_e = (Int16) (Reference - LinPosition);

   /* Sum: controller/si
      # combined # Unit delay: controller/xi */
   X_SCtrl1_xi = (Int16) (((Int16) (SCtrl1_e >> 1)) + X_SCtrl1_xi);

   /* Sum: controller/sPI
      # combined # Gain: controller/Ki
      # combined # Gain: controller/Kp
      # combined # Unit delay: controller/xi */
   SPI = (Int16) (SCtrl1_e + ((Int16) ((((Int32) X_SCtrl1_xi) * 13107) >> 16)));

   /* TargetLink outport: controller/UPI */
   UPI = SPI;
   LOG_VAR(Ctrl, _UPI, UPI);
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Tab1DnMS4I2T1563_Ctrl
 *** 
 ***  DESCRIPTION:
 ***      Generated function for look-up tables with equidistant points.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      UInt8              Nx                  number of axis points
 ***      const Int8 *       z_table             vector with z-values
 ***      UInt8              diffx               step size axis vector, arbitrary or as a shift fact
 or
 ***      Int8               startx              axis vector starting point
 ***      Int8               x                   table input
 ***
 ***  RETURNS:
 ***      Int8
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: equidistant
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***      Behavior at boundaries.............: - (equidistant implementation)
 ***      Starting point.....................: no
 ***      Scaling unit.......................: power of two
 ***
\**************************************************************************************************/
Int8 Tab1DnMS4I2T1563_Ctrl(UInt8 Nx, const Int8 * z_table, UInt8 diffx, Int8 startx, Int8 x)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   Int8 Aux_S8;
   Int8 Aux_S8_a;
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;

   if (x <= startx) {
      /* Saturation. */
      return z_table[0];
   }

   /* Calculate table index. */
   Aux_U8 = (UInt8) (((UInt8) (((UInt8) x) - ((UInt8) startx))) >> diffx);
   if (Aux_U8 >= ((UInt8) (Nx - 1))) {
      return z_table[(UInt8) (Nx - 1)];
   }
   Aux_U8_a = (UInt8) (((UInt8) (((UInt8) x) - ((UInt8) (Aux_U8 << diffx)))) - ((UInt8) startx));
   z_table += Aux_U8;
   Aux_S8 = *(z_table++);
   Aux_S8_a = *z_table;

   /* Interpolation. */
   if (Aux_S8 <= Aux_S8_a) {
      /* Positive slope. */
      Aux_S8 += (((UInt16) (((UInt16) (UInt8) (((UInt8) Aux_S8_a) - ((UInt8) Aux_S8))) * ((UInt16)
       Aux_U8_a))) >> diffx);
   }
   else {
      /* Negative slope. */
      Aux_S8 -= (((UInt16) (((UInt16) (UInt8) (((UInt8) Aux_S8) - ((UInt8) Aux_S8_a))) * ((UInt16)
       Aux_U8_a))) >> diffx);
   }
   return Aux_S8;
}

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Linearization
 *** 
 ***  DESCRIPTION:
 ***      Linearization of measured position signal
 ***      Calculation of the liearized position
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Linearization(void)
{
   /* Switch: controller/Linearization/switch
      controller/Linearization/switch: Omitted comparison with constant.
      # combined # Logical: controller/Linearization/select table
      # combined # Relational: controller/Linearization/pos_GT_max */
   if ((Position >= 3072 /* 3. */) && LinEnableLUT) {
      /* Switch: controller/Linearization/switch
         # combined # TargetLink outport: controller/Linearization/LIN.POS
         # combined # TableLookup: controller/Linearization/Look-Up Table */
      LinPosition = ((Int16) Tab1DnMS4I2T1563_Ctrl(25, (const Int8 *) &(LinTable[0]), 3, -96 /* -12.
       */, (Int8) (Position >> 7))) * 128;
   }
   else {
      /* Switch: controller/Linearization/switch
         # combined # TargetLink outport: controller/Linearization/LIN.POS
         # combined # Gain: controller/Linearization/Gain */
      LinPosition = (Int16) ((((Int32) Position) * ((Int32) LinGain)) >> 7);
   }
   LOG_VAR(Ctrl, _LinPosition, LinPosition);
}

#ifdef __cplusplus
}
#endif

#endif /* CONTROLLER_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
