/*************************************************************************************\
 ***
 *** Simulation S-function frame :  picontroller_sf.c
 *** Code generation unit        :  pipt1/picontroller/Subsystem/picontroller
 ***
 *** Generated by dSPACE TargetLink Version 5.2p1 from 23-Mar-2022
 *** Generation date: 04-Jan-2024 12:51:26
\************************************************************************************/

#ifdef __PICONTROLLER_SF__ 

/* the following #define is used to specify the name of this S-function. */
#define S_FUNCTION_NAME picontroller_sf

/* this S-function is level 2 */
#define S_FUNCTION_LEVEL 2

/* there is a mdlInitializeConditions function */
#define MDL_INITIALIZE_CONDITIONS

/* there is a mdlStart function */
#define MDL_START

#endif /* #ifdef  __PICONTROLLER_SF__ */


/* common TargetLink header files */
#include "tl_generic_sf.h"

/**************************************************************************\
    Variables definitions
***************************************************************************/

/* Arguments for the production code function: picontroller */
static real_T Sa1_REF_LSB[] = { 1.0/2048.0 };
static real_T Sa1_REF_Offset[] = { 0 };
static int_T  Sa1_REF_RootPortNumber[] = { 2 };
static int_T  Sa1_REF_RootPortFirstElement[] = { 1 };

static real_T Sa1_Y_LSB[] = { 1.0/2048.0 };
static real_T Sa1_Y_Offset[] = { 0 };
static int_T  Sa1_Y_RootPortNumber[] = { 3 };
static int_T  Sa1_Y_RootPortFirstElement[] = { 1 };

static real_T Sa1_U_LSB[] = { 1.0/64.0 };
static real_T Sa1_U_Offset[] = { 0 };
static int_T  Sa1_U_RootPortNumber[] = { 1 };
static int_T  Sa1_U_RootPortFirstElement[] = { 1 };

VarDescriptor_tp  fcn__a1_Arg[] = 
{
   {
      "Sa1_REF", eTlSimUInt16, 2, 1, 1, /* name, type and size */
      &Sa1_REF_LSB[0], &Sa1_REF_Offset[0], /* scaling */
      VKE_INPUT, /* variable kind */
      &Sa1_REF_RootPortNumber[0], &Sa1_REF_RootPortFirstElement[0], NULL, /* simulink port info */
      "picontroller", "/picontroller/tl_basetypes/Typedefs/UInt16", "UInt16", /* module name and Typedef object */
      "/Subsystems/picontroller/picontroller/Variables/Sa1_REF", /* Variable object*/
      true, true, true, true, false, false, false, /* bSameLSB, bSameOffset, bSamePort, bSubsequentPortElements, bSelectedVarElements, bIsEnum, bTypeAndSizeUpdateNeeded */
      false, NULL, 0, NULL, NULL, /* bBusPort, bus leaf index list, number of struct widths, struct widths, bus leaf info struct list */
   },
   {
      "Sa1_Y", eTlSimUInt16, 2, 1, 1, /* name, type and size */
      &Sa1_Y_LSB[0], &Sa1_Y_Offset[0], /* scaling */
      VKE_INPUT, /* variable kind */
      &Sa1_Y_RootPortNumber[0], &Sa1_Y_RootPortFirstElement[0], NULL, /* simulink port info */
      "picontroller", "/picontroller/tl_basetypes/Typedefs/UInt16", "UInt16", /* module name and Typedef object */
      "/Subsystems/picontroller/picontroller/Variables/Sa1_Y", /* Variable object*/
      true, true, true, true, false, false, false, /* bSameLSB, bSameOffset, bSamePort, bSubsequentPortElements, bSelectedVarElements, bIsEnum, bTypeAndSizeUpdateNeeded */
      false, NULL, 0, NULL, NULL, /* bBusPort, bus leaf index list, number of struct widths, struct widths, bus leaf info struct list */
   },
   {
      "Sa1_U", eTlSimInt16, 2, 1, 1, /* name, type and size */
      &Sa1_U_LSB[0], &Sa1_U_Offset[0], /* scaling */
      VKE_OUTPUT, /* variable kind */
      &Sa1_U_RootPortNumber[0], &Sa1_U_RootPortFirstElement[0], NULL, /* simulink port info */
      "picontroller", "/picontroller/tl_basetypes/Typedefs/Int16", "Int16", /* module name and Typedef object */
      "/Subsystems/picontroller/picontroller/Variables/Sa1_U", /* Variable object*/
      true, true, true, true, false, false, false, /* bSameLSB, bSameOffset, bSamePort, bSubsequentPortElements, bSelectedVarElements, bIsEnum, bTypeAndSizeUpdateNeeded */
      false, NULL, 0, NULL, NULL, /* bBusPort, bus leaf index list, number of struct widths, struct widths, bus leaf info struct list */
   }
};

/* Functions table */
FcnTableEntry_tp  FcnTable_a[] = 
{
   {
      "picontroller", "CallFcn_a1", ROOT_FCN, TIME_TRIGGERED, 0.0001, 2, 1, 0, fcn__a1_Arg,
      {INVALID_HANDLE, INVALID_HANDLE, INVALID_HANDLE, NULL, NULL}, /* simulation server parameter */
      {0, 0, 0, 0, 0, 0, NULL, NULL}, /* data server parameter */
      1, 0, NULL, NULL, NULL, -1, 0, 1
   }
};
uint_T LengthFcnTable_a = 1;


/* Cyclic tasks table */
FcnTableEntry_tp  TaskTable_a[] = 
{
    NULL 
};
uint_T LengthTaskTable_a = 0;



#ifdef __PICONTROLLER_SF__ 

/* Name of the TL Subsystem */
static const char szTLSubsystemName[] = "picontroller";

/* Subsystem ID */
static const char szSubsystemID[] = "a";

/* Name of the corresponding production code frame */
static const char szProdCodeFrameName[] = "picontroller_pcf";

/* Name of the production code function using to log variable
   with unknow functions relevancy */
static const char szFcnUsedToLogByDefault[] = "picontroller";

/* Timeout enable flag */
static boolean_T bTimeOut = true;

/* Tick duration (for OSEK simulation only) */
static real_T TickDuration = -1;

/* Task and ISR names: needed for execution time and stack size measurement */
static const char ** pTaskNameList = NULL;
static const char ** pIsrNameList = NULL;

/* Simulation frame restart function to init the send/receive communication */
static boolean_T bCallRSFCFileRestartFcn = 0;
static const char szRSFCFileRestart[] = "";

/* System time */
static boolean_T bSetApplSystemTime                = 0;
static boolean_T bCallSetApplSystemTimeCallerFcn   = 0;
static VarDescriptor_tp * ApplSystemTimeDescr = NULL;


/* S-function's interface data */
static const PortInfo_tp InPortsInfo[] = {{1,{22,-1},PDTE_INHERITED,""}, {2,{1,-1},PDTE_INHERITED,""}, {3,{1,-1},PDTE_INHERITED,
   ""}};

static const PortInfo_tp OutPortsInfo[] = {{1,{1,-1},PDTE_DOUBLE,""}};


static SimFrameInfo_tp  RootSimFrameInfo = {
  0.0001,
  3,
  1,
  0,
  0,
  InPortsInfo,
  OutPortsInfo,
  NULL,
  NULL,
};

/***************************************************************************\
    Definitions needed for code coverage test
\***************************************************************************/

boolean_T  bCodeCoverageTest      = false;
real_T     CodeCoverageUpdateRate = 0.0;


/***************************************************************************\
    Definitions needed for exception handling
\***************************************************************************/
#if defined(MATLAB_MEX_FILE)

/* name(s) of production code function(s) */
const char* szFcnNames[] = {
   "picontroller",
};

/* index into function(s) name(s) list */
int nCurrentFcnIdx;

#endif /* if defined(MATLAB_MEX_FILE) */


/* Number of available production code functions, function table and checksum */
static uint_T              nNumberOfFunctions;
static uint_T              nNumberOfCyclicTasks;
static boolean_T           bUseOSEKEmulator = 0;
static uint_T              nCheckSum = 268435491;


/***************************************************************************\
   Function called to initialize the common functions table.
\***************************************************************************/

static void InitFcnTable(FcnTableEntry_tp  ** FcnTable)
{
   FcnTableEntry_tp  * LocalFcnTable = NULL;

   nNumberOfFunctions = LengthFcnTable_a;
   if(nNumberOfFunctions > 0)
   {
      LocalFcnTable = calloc(nNumberOfFunctions, sizeof(FcnTableEntry_tp));

      memcpy(&LocalFcnTable[0], &FcnTable_a[0], LengthFcnTable_a * sizeof(FcnTableEntry_tp));
   }
   *FcnTable = LocalFcnTable;
}


/***************************************************************************\
   Function called to initialize the common cyclic tasks table.
\***************************************************************************/

static void InitTaskTable(FcnTableEntry_tp  ** TaskTable)
{
   FcnTableEntry_tp  * LocalTaskTable = NULL;

   nNumberOfCyclicTasks = LengthTaskTable_a;
   if(nNumberOfCyclicTasks > 0)
   {
      LocalTaskTable = calloc(nNumberOfCyclicTasks, sizeof(FcnTableEntry_tp));

      memcpy(&LocalTaskTable[0], &TaskTable_a[0], LengthTaskTable_a * sizeof(FcnTableEntry_tp));
   }
   *TaskTable = LocalTaskTable;
}


/***************************************************************************\
   Generic code (common for all TargetLink simulation S-Function)
\***************************************************************************/

/* include the generic S-Function code */
#include "tl_generic_sf.c"

#endif /* #ifdef __PICONTROLLER_SF__ */
